blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.detail, name='detail'),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models


class Project(models.Model):
    title = models.CharField(max_length = 100)
    description = models.CharField(max_length = 250)
    image = models.ImageField(upload_to='portfolio/images')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog


def all_blogs(request):
    blogs = Blog.objects.all()
    return render(request , 'blog/all_blogs.html', {'blogs': blogs})


def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html', {'blog': blog})

portfolio/views.py
from django.shortcuts import render
from .models import Project


def home(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/home.html', {'projects': projects})

blog/templates/blog/all_blogs.html
<h1>Blogs</h1>

<h2>Dave has written {{ blogs.count }} blog{{ blogs.count|pluralize }}</h2>

{% for blog in blogs %}

<a href="{% url 'blog:detail' blog.id %}"><h2>{{ blog.title }}</h2></a>
<p>{{ blog.description|striptags|truncatechars:100 }}</p>

{% endfor %}

blog/templates/blog/detail.html
<h1>{{ blog.title }}</h1>
{{ blog.description|safe }}

portfolio/templates/portfolio/home.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<h1>DAVE'S PORTFOLIO</h1>

{% load static %}

<a href="{% url 'blog:all_blogs' %}">Blog</a>
<br>

<img src="{% static 'portfolio/daniil-lebedev-1zL4y0OS0hI-unsplash.jpg' %} " height = 500 width="800">
<br>
<a href="{% static 'portfolio/resume.pdf' %}">Resume</a>

{% for project in projects %}

<h2>{{ project.title }}</h2>

<p>{{ project.description }}</p>
<img src="{{ project.image.url }}" height = 300 width = 500>
{% if project.url %}
<br><a href="{{ project.url }}">Link</a>
{% endif %}
{% endfor %}